---

- hosts: all
  become: true
  tasks:


  - name: install tmux vim qemu-guest-agent zsh
    package:
      name: 
        - tmux
        - vim
        - qemu-guest-agent
        - zsh  
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

