---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    apt:
      update_cache: yes  

  - name: install tmux
    apt:
      name: tmux
      state: latest

  - name: install vim 
    apt:
      name: vim
      state: latest

  - name: install qemu guest agent
    apt:
      name: qemu-guest-agent
      state: latest

