---

- hosts: all
  become: true
  tasks:

  - name: update repository index (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"
  
  - name: update repository index (Ubuntu)
    tags: always
    apt:
      upgrade: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEs/MSCpigE7iFkLu8etRUAFKwB4Db1bXVEGT5NKwUHE ansible_key"

  - name: install tmux vim qemu-guest-agent zsh
    tags: install
    package:
      name: 
        - tmux
        - vim
        - qemu-guest-agent
        - zsh
        - iputils-ping
        - htop
        - neovim
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy tmux config
    tags: bootstrap,tmux 
    copy:
      src: tmux.conf
      dest: /home/chris/.tmux.conf
      owner: chris
      group: chris
      mode: 0644

  - name: change user 'chris' to zsh shell
    tags: bootstrap,zsh
    ansible.builtin.user:
      name: chris
      shell: /bin/zsh

  - name: change user 'root' to zsh shell
    tags: bootstrap,zsh
    ansible.builtin.user:
      name: root
      shell: /bin/zsh

  - name: copy ~/zshrc config
    tags: bootstrap,zsh
    copy:
      src: zshrc_home
      dest: /home/chris/.zshrc
      owner: chris
      group: chris
      mode: 0644

  - name: copy ~/zshrc config root
    tags: bootstrap,zsh
    copy:
      src: zshrc_home
      dest: /root/.zshrc
      owner: root
      group: root
      mode: 0644

  - name: copy ~/zshrc.local config
    tags: bootstarp,zsh
    copy:
      src: zshrc.local
      dest: /home/chris/.zshrc.local
      owner: chris
      group: chris
      mode: 0644

  - name: create neovim config dir
    tags: bootstrap,neovim
    ansible.builtin.file:
      path: /home/chris/.config/nvim
      state: directory
      owner: chris
      group: chris
      mode: 0700

  - name: copy neovim config
    tags: bootstrap,neovim
    copy:
      src: init.vim
      dest: /home/chris/.config/nvim/init.vim
      owner: chris
      group: chris
      mode: 0644


- hosts: nextcloud
  become: true
  tasks:

    - name: Install required system packages
      tags: docker
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      tags: docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      tags: docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      tags: docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      tags: docker
      pip:
        name: docker

    - name: Append the user 'chris' with the group 'admins' and 'developers'
      tags: docker
      ansible.builtin.user:
        name: chris
        groups: docker
        append: yes

