---

- hosts: all
  become: true
  tasks:
  

  - name: install updates (Ubuntu)
    tags: always,update,
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install tmux vim qemu-guest-agent zsh
    tags: install
    package:
      name: 
        - tmux
        - vim
        - qemu-guest-agent
        - zsh  
      state: latest
    when: ansible_distribution == "Ubuntu"


 - name: change user shell to zsh 
    user:
      name: "{{ ansible_user_id }}"  
      shell: /bin/zsh


- hosts: test
  become: true
  tasks:

    
  - name: copy tmux config
    tags: bootstrap,tmux 
    copy:
      src: tmux.conf
      dest: ~/
      owner: chris
      group: chris
      mode: 0644


    # - name: copy /etc/zshrc config
    #   tags: bootstrap,zsh 
    #   copy:
    #     src: zshrc_etc
    #     dest: /ect/zsh/zshrc
    #     owner: root
    #     group: root
    #     mode: 0644
        

  - name: copy ~/zshrc config
    tags: bootstrap,zsh
    copy:
      src: zshrc_home
      dest: /home/chris/.zshrc
      owner: chris
      group: chris
      mode: 0644


  - name: copy ~/zshrc.local config
    tags: bootstarp,zsh
    copy:
      src: zshrc.local
      dest: /home/chris/.zshrc.local
      owner: chris
      group: chris
      mode: 0644
  

- hosts: test
  gather_facts: false
  become: yes
  vars:
    users:
      - blah: blubb
        username: chris
      - blubb: bleh
        username: root
  tasks:
  - name: set shell
    include_tasks: set_shell.yml
    loop: "{{ users }}"