---

- hosts: all
  become: true
  tasks:
  

  - name: install updates (Ubuntu)
    tags: always,update,
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install tmux vim qemu-guest-agent zsh
    tags: install
    package:
      name: 
        - tmux
        - vim
        - qemu-guest-agent
        - zsh
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: test
  become: true
  tasks:

    
  - name: copy tmux config
    tags: bootstrap,tmux 
    copy:
      src: tmux.conf
      dest: /home/chris/.tmux.conf
      owner: chris
      group: chris
      mode: 0644


  - name: change user 'chris' to zsh shell
    ansible.builtin.user:
      name: chris
      shell: /bin/zsh


  - name: change user 'root' to zsh shell
    ansible.builtin.user:
      name: root
      shell: /bin/zsh


  - name: copy ~/zshrc config
    tags: bootstrap,zsh
    copy:
      src: zshrc_home
      dest: /home/chris/.zshrc
      owner: chris
      group: chris
      mode: 0644


  - name: copy ~/zshrc.local config
    tags: bootstarp,zsh
    copy:
      src: zshrc.local
      dest: /home/chris/.zshrc.local
      owner: chris
      group: chris
      mode: 0644
  

