---

- hosts: all
  become: true
  tasks:
  

  - name: install updates (Ubuntu)
    tags: always,update
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install tmux vim qemu-guest-agent zsh
    tags: always,update
    package:
      name: 
        - tmux
        - vim
        - qemu-guest-agent
        - zsh  
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: Change user shell to zsh 
    tags: zsh,chsh
    ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      shell: /bin/zsh




