---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    tags: always,update,
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install tmux vim qemu-guest-agent zsh
    tags: install
    package:
      name: 
        - tmux
        - vim
        - qemu-guest-agent
        - zsh
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:
    
  - name: copy tmux config
    tags: bootstrap,tmux 
    copy:
      src: tmux.conf
      dest: /home/chris/.tmux.conf
      owner: chris
      group: chris
      mode: 0644

  - name: change user 'chris' to zsh shell
    tags: bootstrap,zsh
    ansible.builtin.user:
      name: chris
      shell: /bin/zsh

  - name: change user 'root' to zsh shell
    tags: bootstrap,zsh
    ansible.builtin.user:
      name: root
      shell: /bin/zsh

  - name: copy ~/zshrc config
    tags: bootstrap,zsh
    copy:
      src: zshrc_home
      dest: /home/chris/.zshrc
      owner: chris
      group: chris
      mode: 0644

  - name: copy ~/zshrc.local config
    tags: bootstarp,zsh
    copy:
      src: zshrc.local
      dest: /home/chris/.zshrc.local
      owner: chris
      group: chris
      mode: 0644
  

- hosts: nextcloud
  become: true
  tasks:

    - name: Install required system packages
      tags: docker
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      tags: docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      tags: docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      tags: docker
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      tags: docker
      pip:
        name: docker

    - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      tags: docker
      ansible.builtin.user:
        name: chris
        groups: docker
        append: yes