---
 
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (apt)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: upgrade repository index (apt)
    tags: always
    apt:
      upgrade: "yes"
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: all
  become: true
  roles:
    - base

- hosts: docker_servers
  become: true
  roles:
    - docker_servers
