---
 
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (apt)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
      #I don't think this is needed for all apt distros inlcuding debian
      #    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: docker_servers
  become: true
  roles:
    - docker_servers
