---
 
- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (apt)
    tags: always,update
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

  - name: upgrade packages (apt)
    tags: always,update
    apt:
      upgrade: "yes"
    when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: docker_servers
  tags: docker
  become: true
  roles:
    - docker_servers
    - docker_portainer

- hosts: swap_servers
  tags: test
  become: true
  roles:
    - swapfile