- name: Add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEs/MSCpigE7iFkLu8etRUAFKwB4Db1bXVEGT5NKwUHE ansible_key"

- name: Install tmux vim qemu-guest-agent zsh
  package:
    name: 
      - "{{ tmux }}"
      - "{{ vim }}"
      # - "{{ qemu-guest-agent }}"
      - "{{ zsh }}"
      - "{{ htop }}"
      - "{{ neovim }}"
    state: latest
  when: ansible_distribution == "Ubuntu"
  when: ansible_distribution == "Debian"

- name: Copy tmux config
  copy:
    src: tmux.conf
    dest: /home/chris/.tmux.conf
    owner: chris
    group: chris
    mode: 0644

- name: Change user 'chris' to zsh shell
  tags: bootstrap,zsh
  ansible.builtin.user:
    name: chris
    shell: /bin/zsh

- name: Change user 'root' to zsh shell
  tags: bootstrap,zsh
  ansible.builtin.user:
    name: root
    shell: /bin/zsh

- name: Copy ~/zshrc config
  tags: bootstrap,zsh
  copy:
    src: zshrc_home
    dest: /home/chris/.zshrc
    owner: chris
    group: chris
    mode: 0644

- name: Copy ~/zshrc config root
  tags: bootstrap,zsh
  copy:
    src: zshrc_home
    dest: /root/.zshrc
    owner: root
    group: root
    mode: 0644

- name: Copy ~/zshrc.local config
  tags: bootstarp,zsh
  copy:
    src: zshrc.local
    dest: /home/chris/.zshrc.local
    owner: chris
    group: chris
    mode: 0644

- name: Create neovim config dir
  tags: bootstrap,neovim
  ansible.builtin.file:
    path: /home/chris/.config/nvim
    state: directory
    owner: chris
    group: chris
    mode: 0700

- name: Copy neovim config
  tags: bootstrap,neovim
  copy:
    src: init.vim
    dest: /home/chris/.config/nvim/init.vim
    owner: chris
    group: chris
    mode: 0644
